# Networking binding and tagging is handled by the engine
version: "3"
services:
  app-db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=appDB
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - app-db